{
 "cells": [
  {
   "cell_type": "code",
   "execution_count": 5,
   "metadata": {
    "scrolled": false
   },
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "<pymongo.cursor.Cursor object at 0x7f2fb3ab8240>\n",
      " * Serving Flask app \"__main__\" (lazy loading)\n",
      " * Environment: production\n",
      "   WARNING: This is a development server. Do not use it in a production deployment.\n",
      "   Use a production WSGI server instead.\n",
      " * Debug mode: off\n"
     ]
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      " * Running on http://127.0.0.1:8050/ (Press CTRL+C to quit)\n",
      "127.0.0.1 - - [20/Apr/2023 22:20:21] \"\u001b[37mGET / HTTP/1.1\u001b[0m\" 200 -\n",
      "127.0.0.1 - - [20/Apr/2023 22:20:21] \"\u001b[37mGET /_dash-component-suites/dash_renderer/react@16.v1_3_0m1588250875.13.0.min.js HTTP/1.1\u001b[0m\" 200 -\n",
      "127.0.0.1 - - [20/Apr/2023 22:20:21] \"\u001b[37mGET /_dash-component-suites/dash_renderer/polyfill@7.v1_3_0m1588250875.8.7.min.js HTTP/1.1\u001b[0m\" 200 -\n",
      "127.0.0.1 - - [20/Apr/2023 22:20:21] \"\u001b[37mGET /_dash-component-suites/dash_renderer/prop-types@15.v1_3_0m1588250875.7.2.min.js HTTP/1.1\u001b[0m\" 200 -\n",
      "127.0.0.1 - - [20/Apr/2023 22:20:21] \"\u001b[37mGET /_dash-component-suites/dash_renderer/react-dom@16.v1_3_0m1588250875.13.0.min.js HTTP/1.1\u001b[0m\" 200 -\n",
      "127.0.0.1 - - [20/Apr/2023 22:20:21] \"\u001b[37mGET /_dash-component-suites/dash_core_components/dash_core_components-shared.v1_9_0m1588250878.js HTTP/1.1\u001b[0m\" 200 -\n",
      "127.0.0.1 - - [20/Apr/2023 22:20:21] \"\u001b[37mGET /_dash-component-suites/dash_core_components/dash_core_components.v1_9_0m1588250878.min.js HTTP/1.1\u001b[0m\" 200 -\n",
      "127.0.0.1 - - [20/Apr/2023 22:20:21] \"\u001b[37mGET /_dash-component-suites/dash_table/bundle.v4_6_2m1585840851.js HTTP/1.1\u001b[0m\" 200 -\n",
      "127.0.0.1 - - [20/Apr/2023 22:20:21] \"\u001b[37mGET /_dash-component-suites/dash_html_components/dash_html_components.v1_0_3m1585840840.min.js HTTP/1.1\u001b[0m\" 200 -\n",
      "127.0.0.1 - - [20/Apr/2023 22:20:21] \"\u001b[37mGET /_dash-component-suites/dash_renderer/dash_renderer.v1_3_0m1588250875.min.js HTTP/1.1\u001b[0m\" 200 -\n",
      "127.0.0.1 - - [20/Apr/2023 22:20:21] \"\u001b[37mGET /_dash-component-suites/dash_leaflet/dash_leaflet.v0_0_9m1588250815.min.js HTTP/1.1\u001b[0m\" 200 -\n",
      "127.0.0.1 - - [20/Apr/2023 22:20:21] \"\u001b[37mGET /_dash-dependencies HTTP/1.1\u001b[0m\" 200 -\n",
      "127.0.0.1 - - [20/Apr/2023 22:20:21] \"\u001b[37mGET /_favicon.ico?v=1.10.0 HTTP/1.1\u001b[0m\" 200 -\n",
      "127.0.0.1 - - [20/Apr/2023 22:20:21] \"\u001b[37mGET /_dash-layout HTTP/1.1\u001b[0m\" 200 -\n"
     ]
    },
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "<pymongo.cursor.Cursor object at 0x7f2fb33774a8>\n",
      "Exception on /_dash-update-component [POST]\n",
      "Traceback (most recent call last):\n",
      "  File \"/usr/local/anaconda/lib/python3.6/site-packages/flask/app.py\", line 2446, in wsgi_app\n",
      "    response = self.full_dispatch_request()\n",
      "  File \"/usr/local/anaconda/lib/python3.6/site-packages/flask/app.py\", line 1951, in full_dispatch_request\n",
      "    rv = self.handle_user_exception(e)\n",
      "  File \"/usr/local/anaconda/lib/python3.6/site-packages/flask/app.py\", line 1820, in handle_user_exception\n",
      "    reraise(exc_type, exc_value, tb)\n",
      "  File \"/usr/local/anaconda/lib/python3.6/site-packages/flask/_compat.py\", line 39, in reraise\n",
      "    raise value\n",
      "  File \"/usr/local/anaconda/lib/python3.6/site-packages/flask/app.py\", line 1949, in full_dispatch_request\n",
      "    rv = self.dispatch_request()\n",
      "  File \"/usr/local/anaconda/lib/python3.6/site-packages/flask/app.py\", line 1935, in dispatch_request\n",
      "    return self.view_functions[rule.endpoint](**req.view_args)\n",
      "  File \"/usr/local/anaconda/lib/python3.6/site-packages/dash/dash.py\", line 1407, in dispatch\n",
      "    response.set_data(self.callback_map[output][\"callback\"](*args))\n",
      "  File \"/usr/local/anaconda/lib/python3.6/site-packages/dash/dash.py\", line 1294, in add_context\n",
      "    output_value = func(*args, **kwargs)  # %% callback invoked %%\n",
      "  File \"<ipython-input-5-2c66faee6993>\", line 194, in update_map\n",
      "    row_ids[0] = row_ids[len(row_ids) - 1]\n",
      "TypeError: object of type 'NoneType' has no len()\n",
      "Exception on /_dash-update-component [POST]\n",
      "Traceback (most recent call last):\n",
      "  File \"/usr/local/anaconda/lib/python3.6/site-packages/flask/app.py\", line 2446, in wsgi_app\n",
      "    response = self.full_dispatch_request()\n",
      "  File \"/usr/local/anaconda/lib/python3.6/site-packages/flask/app.py\", line 1951, in full_dispatch_request\n",
      "    rv = self.handle_user_exception(e)\n",
      "  File \"/usr/local/anaconda/lib/python3.6/site-packages/flask/app.py\", line 1820, in handle_user_exception\n",
      "    reraise(exc_type, exc_value, tb)\n",
      "  File \"/usr/local/anaconda/lib/python3.6/site-packages/flask/_compat.py\", line 39, in reraise\n",
      "    raise value\n",
      "  File \"/usr/local/anaconda/lib/python3.6/site-packages/flask/app.py\", line 1949, in full_dispatch_request\n",
      "    rv = self.dispatch_request()\n",
      "  File \"/usr/local/anaconda/lib/python3.6/site-packages/flask/app.py\", line 1935, in dispatch_request\n",
      "    return self.view_functions[rule.endpoint](**req.view_args)\n",
      "  File \"/usr/local/anaconda/lib/python3.6/site-packages/dash/dash.py\", line 1407, in dispatch\n",
      "    response.set_data(self.callback_map[output][\"callback\"](*args))\n",
      "  File \"/usr/local/anaconda/lib/python3.6/site-packages/dash/dash.py\", line 1294, in add_context\n",
      "    output_value = func(*args, **kwargs)  # %% callback invoked %%\n",
      "  File \"<ipython-input-5-2c66faee6993>\", line 194, in update_map\n",
      "    row_ids[0] = row_ids[len(row_ids) - 1]\n",
      "TypeError: object of type 'NoneType' has no len()\n"
     ]
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "127.0.0.1 - - [20/Apr/2023 22:20:22] \"\u001b[37mPOST /_dash-update-component HTTP/1.1\u001b[0m\" 200 -\n"
     ]
    },
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "Exception on /_dash-update-component [POST]\n",
      "Traceback (most recent call last):\n",
      "  File \"/usr/local/anaconda/lib/python3.6/site-packages/flask/app.py\", line 2446, in wsgi_app\n",
      "    response = self.full_dispatch_request()\n",
      "  File \"/usr/local/anaconda/lib/python3.6/site-packages/flask/app.py\", line 1951, in full_dispatch_request\n",
      "    rv = self.handle_user_exception(e)\n",
      "  File \"/usr/local/anaconda/lib/python3.6/site-packages/flask/app.py\", line 1820, in handle_user_exception\n",
      "    reraise(exc_type, exc_value, tb)\n",
      "  File \"/usr/local/anaconda/lib/python3.6/site-packages/flask/_compat.py\", line 39, in reraise\n",
      "    raise value\n",
      "  File \"/usr/local/anaconda/lib/python3.6/site-packages/flask/app.py\", line 1949, in full_dispatch_request\n",
      "    rv = self.dispatch_request()\n",
      "  File \"/usr/local/anaconda/lib/python3.6/site-packages/flask/app.py\", line 1935, in dispatch_request\n",
      "    return self.view_functions[rule.endpoint](**req.view_args)\n",
      "  File \"/usr/local/anaconda/lib/python3.6/site-packages/dash/dash.py\", line 1407, in dispatch\n",
      "    response.set_data(self.callback_map[output][\"callback\"](*args))\n",
      "  File \"/usr/local/anaconda/lib/python3.6/site-packages/dash/dash.py\", line 1294, in add_context\n",
      "    output_value = func(*args, **kwargs)  # %% callback invoked %%\n",
      "  File \"<ipython-input-5-2c66faee6993>\", line 182, in update_graphs\n",
      "    figure = px.histogram(dff, x='breed')\n",
      "  File \"/usr/local/anaconda/lib/python3.6/site-packages/plotly/express/_chart_types.py\", line 372, in histogram\n",
      "    layout_patch=dict(barmode=barmode, barnorm=barnorm),\n",
      "  File \"/usr/local/anaconda/lib/python3.6/site-packages/plotly/express/_core.py\", line 1368, in make_figure\n",
      "    args, constructor, trace_patch\n",
      "  File \"/usr/local/anaconda/lib/python3.6/site-packages/plotly/express/_core.py\", line 1211, in infer_config\n",
      "    args = build_dataframe(args, all_attrables, array_attrables)\n",
      "  File \"/usr/local/anaconda/lib/python3.6/site-packages/plotly/express/_core.py\", line 975, in build_dataframe\n",
      "    raise ValueError(err_msg)\n",
      "ValueError: Value of 'x' is not the name of a column in 'data_frame'. Expected one of [] but received: breed\n",
      "Exception on /_dash-update-component [POST]\n",
      "Traceback (most recent call last):\n",
      "  File \"/usr/local/anaconda/lib/python3.6/site-packages/flask/app.py\", line 2446, in wsgi_app\n",
      "    response = self.full_dispatch_request()\n",
      "  File \"/usr/local/anaconda/lib/python3.6/site-packages/flask/app.py\", line 1951, in full_dispatch_request\n",
      "    rv = self.handle_user_exception(e)\n",
      "  File \"/usr/local/anaconda/lib/python3.6/site-packages/flask/app.py\", line 1820, in handle_user_exception\n",
      "    reraise(exc_type, exc_value, tb)\n",
      "  File \"/usr/local/anaconda/lib/python3.6/site-packages/flask/_compat.py\", line 39, in reraise\n",
      "    raise value\n",
      "  File \"/usr/local/anaconda/lib/python3.6/site-packages/flask/app.py\", line 1949, in full_dispatch_request\n",
      "    rv = self.dispatch_request()\n",
      "  File \"/usr/local/anaconda/lib/python3.6/site-packages/flask/app.py\", line 1935, in dispatch_request\n",
      "    return self.view_functions[rule.endpoint](**req.view_args)\n",
      "  File \"/usr/local/anaconda/lib/python3.6/site-packages/dash/dash.py\", line 1407, in dispatch\n",
      "    response.set_data(self.callback_map[output][\"callback\"](*args))\n",
      "  File \"/usr/local/anaconda/lib/python3.6/site-packages/dash/dash.py\", line 1294, in add_context\n",
      "    output_value = func(*args, **kwargs)  # %% callback invoked %%\n",
      "  File \"<ipython-input-5-2c66faee6993>\", line 194, in update_map\n",
      "    row_ids[0] = row_ids[len(row_ids) - 1]\n",
      "TypeError: object of type 'NoneType' has no len()\n",
      "Exception on /_dash-update-component [POST]\n",
      "Traceback (most recent call last):\n",
      "  File \"/usr/local/anaconda/lib/python3.6/site-packages/flask/app.py\", line 2446, in wsgi_app\n",
      "    response = self.full_dispatch_request()\n",
      "  File \"/usr/local/anaconda/lib/python3.6/site-packages/flask/app.py\", line 1951, in full_dispatch_request\n",
      "    rv = self.handle_user_exception(e)\n",
      "  File \"/usr/local/anaconda/lib/python3.6/site-packages/flask/app.py\", line 1820, in handle_user_exception\n",
      "    reraise(exc_type, exc_value, tb)\n",
      "  File \"/usr/local/anaconda/lib/python3.6/site-packages/flask/_compat.py\", line 39, in reraise\n",
      "    raise value\n",
      "  File \"/usr/local/anaconda/lib/python3.6/site-packages/flask/app.py\", line 1949, in full_dispatch_request\n",
      "    rv = self.dispatch_request()\n",
      "  File \"/usr/local/anaconda/lib/python3.6/site-packages/flask/app.py\", line 1935, in dispatch_request\n",
      "    return self.view_functions[rule.endpoint](**req.view_args)\n",
      "  File \"/usr/local/anaconda/lib/python3.6/site-packages/dash/dash.py\", line 1407, in dispatch\n",
      "    response.set_data(self.callback_map[output][\"callback\"](*args))\n",
      "  File \"/usr/local/anaconda/lib/python3.6/site-packages/dash/dash.py\", line 1294, in add_context\n",
      "    output_value = func(*args, **kwargs)  # %% callback invoked %%\n",
      "  File \"<ipython-input-5-2c66faee6993>\", line 182, in update_graphs\n",
      "    figure = px.histogram(dff, x='breed')\n",
      "  File \"/usr/local/anaconda/lib/python3.6/site-packages/plotly/express/_chart_types.py\", line 372, in histogram\n",
      "    layout_patch=dict(barmode=barmode, barnorm=barnorm),\n",
      "  File \"/usr/local/anaconda/lib/python3.6/site-packages/plotly/express/_core.py\", line 1368, in make_figure\n",
      "    args, constructor, trace_patch\n",
      "  File \"/usr/local/anaconda/lib/python3.6/site-packages/plotly/express/_core.py\", line 1211, in infer_config\n",
      "    args = build_dataframe(args, all_attrables, array_attrables)\n",
      "  File \"/usr/local/anaconda/lib/python3.6/site-packages/plotly/express/_core.py\", line 975, in build_dataframe\n",
      "    raise ValueError(err_msg)\n",
      "ValueError: Value of 'x' is not the name of a column in 'data_frame'. Expected one of [] but received: breed\n"
     ]
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "127.0.0.1 - - [20/Apr/2023 22:20:22] \"\u001b[37mPOST /_dash-update-component HTTP/1.1\u001b[0m\" 200 -\n"
     ]
    },
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "Exception on /_dash-update-component [POST]\n",
      "Traceback (most recent call last):\n",
      "  File \"/usr/local/anaconda/lib/python3.6/site-packages/flask/app.py\", line 2446, in wsgi_app\n",
      "    response = self.full_dispatch_request()\n",
      "  File \"/usr/local/anaconda/lib/python3.6/site-packages/flask/app.py\", line 1951, in full_dispatch_request\n",
      "    rv = self.handle_user_exception(e)\n",
      "  File \"/usr/local/anaconda/lib/python3.6/site-packages/flask/app.py\", line 1820, in handle_user_exception\n",
      "    reraise(exc_type, exc_value, tb)\n",
      "  File \"/usr/local/anaconda/lib/python3.6/site-packages/flask/_compat.py\", line 39, in reraise\n",
      "    raise value\n",
      "  File \"/usr/local/anaconda/lib/python3.6/site-packages/flask/app.py\", line 1949, in full_dispatch_request\n",
      "    rv = self.dispatch_request()\n",
      "  File \"/usr/local/anaconda/lib/python3.6/site-packages/flask/app.py\", line 1935, in dispatch_request\n",
      "    return self.view_functions[rule.endpoint](**req.view_args)\n",
      "  File \"/usr/local/anaconda/lib/python3.6/site-packages/dash/dash.py\", line 1407, in dispatch\n",
      "    response.set_data(self.callback_map[output][\"callback\"](*args))\n",
      "  File \"/usr/local/anaconda/lib/python3.6/site-packages/dash/dash.py\", line 1294, in add_context\n",
      "    output_value = func(*args, **kwargs)  # %% callback invoked %%\n",
      "  File \"<ipython-input-5-2c66faee6993>\", line 194, in update_map\n",
      "    row_ids[0] = row_ids[len(row_ids) - 1]\n",
      "TypeError: object of type 'NoneType' has no len()\n",
      "Exception on /_dash-update-component [POST]\n",
      "Traceback (most recent call last):\n",
      "  File \"/usr/local/anaconda/lib/python3.6/site-packages/flask/app.py\", line 2446, in wsgi_app\n",
      "    response = self.full_dispatch_request()\n",
      "  File \"/usr/local/anaconda/lib/python3.6/site-packages/flask/app.py\", line 1951, in full_dispatch_request\n",
      "    rv = self.handle_user_exception(e)\n",
      "  File \"/usr/local/anaconda/lib/python3.6/site-packages/flask/app.py\", line 1820, in handle_user_exception\n",
      "    reraise(exc_type, exc_value, tb)\n",
      "  File \"/usr/local/anaconda/lib/python3.6/site-packages/flask/_compat.py\", line 39, in reraise\n",
      "    raise value\n",
      "  File \"/usr/local/anaconda/lib/python3.6/site-packages/flask/app.py\", line 1949, in full_dispatch_request\n",
      "    rv = self.dispatch_request()\n",
      "  File \"/usr/local/anaconda/lib/python3.6/site-packages/flask/app.py\", line 1935, in dispatch_request\n",
      "    return self.view_functions[rule.endpoint](**req.view_args)\n",
      "  File \"/usr/local/anaconda/lib/python3.6/site-packages/dash/dash.py\", line 1407, in dispatch\n",
      "    response.set_data(self.callback_map[output][\"callback\"](*args))\n",
      "  File \"/usr/local/anaconda/lib/python3.6/site-packages/dash/dash.py\", line 1294, in add_context\n",
      "    output_value = func(*args, **kwargs)  # %% callback invoked %%\n",
      "  File \"<ipython-input-5-2c66faee6993>\", line 182, in update_graphs\n",
      "    figure = px.histogram(dff, x='breed')\n",
      "  File \"/usr/local/anaconda/lib/python3.6/site-packages/plotly/express/_chart_types.py\", line 372, in histogram\n",
      "    layout_patch=dict(barmode=barmode, barnorm=barnorm),\n",
      "  File \"/usr/local/anaconda/lib/python3.6/site-packages/plotly/express/_core.py\", line 1368, in make_figure\n",
      "    args, constructor, trace_patch\n",
      "  File \"/usr/local/anaconda/lib/python3.6/site-packages/plotly/express/_core.py\", line 1211, in infer_config\n",
      "    args = build_dataframe(args, all_attrables, array_attrables)\n",
      "  File \"/usr/local/anaconda/lib/python3.6/site-packages/plotly/express/_core.py\", line 975, in build_dataframe\n",
      "    raise ValueError(err_msg)\n",
      "ValueError: Value of 'x' is not the name of a column in 'data_frame'. Expected one of [] but received: breed\n",
      "Exception on /_dash-update-component [POST]\n",
      "Traceback (most recent call last):\n",
      "  File \"/usr/local/anaconda/lib/python3.6/site-packages/flask/app.py\", line 2446, in wsgi_app\n",
      "    response = self.full_dispatch_request()\n",
      "  File \"/usr/local/anaconda/lib/python3.6/site-packages/flask/app.py\", line 1951, in full_dispatch_request\n",
      "    rv = self.handle_user_exception(e)\n",
      "  File \"/usr/local/anaconda/lib/python3.6/site-packages/flask/app.py\", line 1820, in handle_user_exception\n",
      "    reraise(exc_type, exc_value, tb)\n",
      "  File \"/usr/local/anaconda/lib/python3.6/site-packages/flask/_compat.py\", line 39, in reraise\n",
      "    raise value\n",
      "  File \"/usr/local/anaconda/lib/python3.6/site-packages/flask/app.py\", line 1949, in full_dispatch_request\n",
      "    rv = self.dispatch_request()\n",
      "  File \"/usr/local/anaconda/lib/python3.6/site-packages/flask/app.py\", line 1935, in dispatch_request\n",
      "    return self.view_functions[rule.endpoint](**req.view_args)\n",
      "  File \"/usr/local/anaconda/lib/python3.6/site-packages/dash/dash.py\", line 1407, in dispatch\n",
      "    response.set_data(self.callback_map[output][\"callback\"](*args))\n",
      "  File \"/usr/local/anaconda/lib/python3.6/site-packages/dash/dash.py\", line 1294, in add_context\n",
      "    output_value = func(*args, **kwargs)  # %% callback invoked %%\n",
      "  File \"<ipython-input-5-2c66faee6993>\", line 194, in update_map\n",
      "    row_ids[0] = row_ids[len(row_ids) - 1]\n",
      "TypeError: object of type 'NoneType' has no len()\n",
      "Exception on /_dash-update-component [POST]\n",
      "Traceback (most recent call last):\n",
      "  File \"/usr/local/anaconda/lib/python3.6/site-packages/flask/app.py\", line 2446, in wsgi_app\n",
      "    response = self.full_dispatch_request()\n",
      "  File \"/usr/local/anaconda/lib/python3.6/site-packages/flask/app.py\", line 1951, in full_dispatch_request\n",
      "    rv = self.handle_user_exception(e)\n",
      "  File \"/usr/local/anaconda/lib/python3.6/site-packages/flask/app.py\", line 1820, in handle_user_exception\n",
      "    reraise(exc_type, exc_value, tb)\n",
      "  File \"/usr/local/anaconda/lib/python3.6/site-packages/flask/_compat.py\", line 39, in reraise\n",
      "    raise value\n",
      "  File \"/usr/local/anaconda/lib/python3.6/site-packages/flask/app.py\", line 1949, in full_dispatch_request\n",
      "    rv = self.dispatch_request()\n",
      "  File \"/usr/local/anaconda/lib/python3.6/site-packages/flask/app.py\", line 1935, in dispatch_request\n",
      "    return self.view_functions[rule.endpoint](**req.view_args)\n",
      "  File \"/usr/local/anaconda/lib/python3.6/site-packages/dash/dash.py\", line 1407, in dispatch\n",
      "    response.set_data(self.callback_map[output][\"callback\"](*args))\n",
      "  File \"/usr/local/anaconda/lib/python3.6/site-packages/dash/dash.py\", line 1294, in add_context\n",
      "    output_value = func(*args, **kwargs)  # %% callback invoked %%\n",
      "  File \"<ipython-input-5-2c66faee6993>\", line 182, in update_graphs\n",
      "    figure = px.histogram(dff, x='breed')\n",
      "  File \"/usr/local/anaconda/lib/python3.6/site-packages/plotly/express/_chart_types.py\", line 372, in histogram\n",
      "    layout_patch=dict(barmode=barmode, barnorm=barnorm),\n",
      "  File \"/usr/local/anaconda/lib/python3.6/site-packages/plotly/express/_core.py\", line 1368, in make_figure\n",
      "    args, constructor, trace_patch\n",
      "  File \"/usr/local/anaconda/lib/python3.6/site-packages/plotly/express/_core.py\", line 1211, in infer_config\n",
      "    args = build_dataframe(args, all_attrables, array_attrables)\n",
      "  File \"/usr/local/anaconda/lib/python3.6/site-packages/plotly/express/_core.py\", line 975, in build_dataframe\n",
      "    raise ValueError(err_msg)\n",
      "ValueError: Value of 'x' is not the name of a column in 'data_frame'. Expected one of [] but received: breed\n"
     ]
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "127.0.0.1 - - [20/Apr/2023 22:20:22] \"\u001b[1m\u001b[35mPOST /_dash-update-component HTTP/1.1\u001b[0m\" 500 -\n"
     ]
    },
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "Exception on /_dash-update-component [POST]\n",
      "Traceback (most recent call last):\n",
      "  File \"/usr/local/anaconda/lib/python3.6/site-packages/flask/app.py\", line 2446, in wsgi_app\n",
      "    response = self.full_dispatch_request()\n",
      "  File \"/usr/local/anaconda/lib/python3.6/site-packages/flask/app.py\", line 1951, in full_dispatch_request\n",
      "    rv = self.handle_user_exception(e)\n",
      "  File \"/usr/local/anaconda/lib/python3.6/site-packages/flask/app.py\", line 1820, in handle_user_exception\n",
      "    reraise(exc_type, exc_value, tb)\n",
      "  File \"/usr/local/anaconda/lib/python3.6/site-packages/flask/_compat.py\", line 39, in reraise\n",
      "    raise value\n",
      "  File \"/usr/local/anaconda/lib/python3.6/site-packages/flask/app.py\", line 1949, in full_dispatch_request\n",
      "    rv = self.dispatch_request()\n",
      "  File \"/usr/local/anaconda/lib/python3.6/site-packages/flask/app.py\", line 1935, in dispatch_request\n",
      "    return self.view_functions[rule.endpoint](**req.view_args)\n",
      "  File \"/usr/local/anaconda/lib/python3.6/site-packages/dash/dash.py\", line 1407, in dispatch\n",
      "    response.set_data(self.callback_map[output][\"callback\"](*args))\n",
      "  File \"/usr/local/anaconda/lib/python3.6/site-packages/dash/dash.py\", line 1294, in add_context\n",
      "    output_value = func(*args, **kwargs)  # %% callback invoked %%\n",
      "  File \"<ipython-input-5-2c66faee6993>\", line 182, in update_graphs\n",
      "    figure = px.histogram(dff, x='breed')\n",
      "  File \"/usr/local/anaconda/lib/python3.6/site-packages/plotly/express/_chart_types.py\", line 372, in histogram\n",
      "    layout_patch=dict(barmode=barmode, barnorm=barnorm),\n",
      "  File \"/usr/local/anaconda/lib/python3.6/site-packages/plotly/express/_core.py\", line 1368, in make_figure\n",
      "    args, constructor, trace_patch\n",
      "  File \"/usr/local/anaconda/lib/python3.6/site-packages/plotly/express/_core.py\", line 1211, in infer_config\n",
      "    args = build_dataframe(args, all_attrables, array_attrables)\n",
      "  File \"/usr/local/anaconda/lib/python3.6/site-packages/plotly/express/_core.py\", line 975, in build_dataframe\n",
      "    raise ValueError(err_msg)\n",
      "ValueError: Value of 'x' is not the name of a column in 'data_frame'. Expected one of [] but received: breed\n"
     ]
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "127.0.0.1 - - [20/Apr/2023 22:20:22] \"\u001b[37mPOST /_dash-update-component HTTP/1.1\u001b[0m\" 200 -\n",
      "127.0.0.1 - - [20/Apr/2023 22:20:22] \"\u001b[1m\u001b[35mPOST /_dash-update-component HTTP/1.1\u001b[0m\" 500 -\n",
      "127.0.0.1 - - [20/Apr/2023 22:20:22] \"\u001b[37mPOST /_dash-update-component HTTP/1.1\u001b[0m\" 200 -\n",
      "127.0.0.1 - - [20/Apr/2023 22:20:22] \"\u001b[37mPOST /_dash-update-component HTTP/1.1\u001b[0m\" 200 -\n",
      "127.0.0.1 - - [20/Apr/2023 22:20:23] \"\u001b[37mPOST /_dash-update-component HTTP/1.1\u001b[0m\" 200 -\n",
      "127.0.0.1 - - [20/Apr/2023 22:41:10] \"\u001b[37mPOST /_dash-update-component HTTP/1.1\u001b[0m\" 200 -\n"
     ]
    }
   ],
   "source": [
    "from jupyter_plotly_dash import JupyterDash\n",
    "\n",
    "import dash\n",
    "import dash_leaflet as dl\n",
    "import dash_core_components as dcc\n",
    "import dash_html_components as html\n",
    "import plotly.express as px\n",
    "import dash_table as dt\n",
    "from dash.dependencies import Input, Output, State\n",
    "\n",
    "import os\n",
    "import numpy as np\n",
    "import pandas as pd\n",
    "from pymongo import MongoClient\n",
    "from bson.json_util import dumps\n",
    "import base64\n",
    "\n",
    "import animal_shelter\n",
    "\n",
    "\n",
    "# Importing AnimalShelter class \n",
    "from animal_shelter import AnimalShelter\n",
    "\n",
    "\n",
    "\n",
    "###########################\n",
    "# Data Manipulation / Model\n",
    "###########################\n",
    "username = \"aacUser\"\n",
    "password = \"animals\"\n",
    "animals = AnimalShelter(username, password)\n",
    "\n",
    "\n",
    "# class read method must support return of cursor object \n",
    "df = pd.DataFrame.from_records(animals.read({}))\n",
    "\n",
    "\n",
    "#########################\n",
    "# Dashboard Layout / View\n",
    "#########################\n",
    "# create dash application\n",
    "\n",
    "external_stylesheets = ['https://codepen.io/chriddyp/pen/bWLwgP.css']\n",
    "app = dash.Dash(__name__, external_stylesheets=external_stylesheets)\n",
    "\n",
    "\n",
    "image_filename = 'Grazioso Salvare Logo.png' # replace with your own image\n",
    "encoded_image = base64.b64encode(open(image_filename, 'rb').read())\n",
    "                               \n",
    "app.layout = html.Div([\n",
    "    html.Div(id='hidden-div', style={'display':'none'}),\n",
    "    html.Center(html.B(html.H1('SNHU CS-340 Dashboard'))),\n",
    "    html.Center(html.B(html.H1('Jacob Silberstein Project 2 Dashboard'))),\n",
    "    html.Hr(),\n",
    "    html.Center(html.Img(id='customer-image',src='data:image/png;base64,{}'.format(encoded_image.decode()),alt='customer image')),\n",
    "    html.Div(      \n",
    "        dcc.RadioItems(\n",
    "            id='filter-type',\n",
    "            options=[\n",
    "                {'label': 'Water Rescue unit', 'value': 'water'},\n",
    "                {'label': 'Wilderness Exploration and Recovery Unit', 'value': 'Wild'},\n",
    "                {'label': 'Disaster Relief and Individual Tracking Unit', 'value': 'disaster'},\n",
    "                {'label': 'Reset', 'value': 'reset'}\n",
    "            ],\n",
    "            value='reset'\n",
    "        )\n",
    "        \n",
    "    ),\n",
    "    html.Hr(),\n",
    "    dt.DataTable(\n",
    "        id='datatable-id',\n",
    "        columns=[\n",
    "            {\"name\": i, \"id\": i, \"deletable\": False, \"selectable\": True} for i in df.columns\n",
    "        ],\n",
    "        data=df.to_dict('records'),\n",
    "        # Starts on page 0 and allows up to 10 rows.\n",
    "        #Columns and Rows may be selected but not deleted/edited\n",
    "        editable=False,\n",
    "        sort_action=\"native\",\n",
    "        sort_mode=\"multi\",\n",
    "        column_selectable=True,\n",
    "        row_selectable=True,\n",
    "        row_deletable=False,\n",
    "        selected_columns=[],\n",
    "        selected_rows=[0],\n",
    "        page_action=\"native\",\n",
    "        page_current= 0,\n",
    "        page_size= 10,\n",
    "    ),\n",
    "    html.Br(),\n",
    "    html.Hr(),\n",
    "    #This sets up the dashboard so that your chart and your geolocation chart are side-by-side\n",
    "    html.Div(className='row',\n",
    "         style={'display' : 'flex'},\n",
    "             children=[\n",
    "        html.Div(\n",
    "            id='graph-id',\n",
    "            className='col s12 m6',\n",
    "\n",
    "            ),\n",
    "        html.Div(\n",
    "            id='map-id',\n",
    "            className='col s12 m6',\n",
    "            )\n",
    "        ])\n",
    "])\n",
    "\n",
    "#############################################\n",
    "# Interaction Between Components / Controller\n",
    "#############################################\n",
    "\n",
    "\n",
    "\n",
    "# Radio button filters\n",
    "@app.callback([Output('datatable-id','data'),\n",
    "               Output('datatable-id','columns')],\n",
    "              [Input('filter-type', 'value')])\n",
    "def update_dashboard(filter_type):\n",
    "        # Water Rescue filter\n",
    "        if filter_type == 'water':\n",
    "            df = pd.DataFrame.from_records(animals.read({\n",
    "                \"animal_type\": \"Dog\",\n",
    "                \"breed\": {\"$in\": [\"Labrador Retriever Mix\",\"Chesapeake Bay Retriever\", \"Newfoundland\"\n",
    "                                 ]},\n",
    "                \"sex_upon_outcome\": \"Intact Female\",\n",
    "                \"age_upon_outcome_in_weeks\": {\"$gte\":26.0, \"$lte\":156.0}\n",
    "            }))\n",
    "        # Wilderness Exploration and Recovery Unit Filter\n",
    "        elif filter_type == 'Wild':\n",
    "            df = pd.DataFrame.from_records(animals.read({\n",
    "                \"animal_type\": \"Dog\",\n",
    "                \"breed\": {\"$in\": [\"German Shepard\",\"Alaskan Malamute\",\"Old English Sheepdog\", \n",
    "                                  \"Siberian Husky\", \"Rottweiler\"\n",
    "                                 ]},\n",
    "                \"sex_upon_outcome\": \"Intact Male\",\n",
    "                \"age_upon_outcome_in_weeks\": {\"$gte\":26.0, \"$lte\":156.0}\n",
    "            }))\n",
    "            \n",
    "        # Disaster Relief and Individual Tracking Unit Filter\n",
    "        elif filter_type == 'disaster':\n",
    "            df = pd.DataFrame.from_records(animals.read({\n",
    "                \"animal_type\": \"Dog\",\n",
    "                \"breed\": {\"$in\": [\"Doberman Pinscher\",\"German Shepard\",\"Golden Retriever\", \n",
    "                                  \"Bloodhound\",\"Rottweiler\"\n",
    "                                 ]},\n",
    "                \"sex_upon_outcome\": \"Intact Male\",\n",
    "                \"age_upon_outcome_in_weeks\": {\"$gte\":20.0, \"$lte\":300.0}\n",
    "            }))\n",
    "            \n",
    "        # Reset to no filter\n",
    "        else:\n",
    "            df = pd.DataFrame.from_records(animals.read({}))\n",
    "        #Restores to original settings as of opening Dash\n",
    "        columns=[{\"name\": i, \"id\": i, \"deletable\": False, \"selectable\": True} for i in df.columns]\n",
    "        data=df.to_dict('records')\n",
    "        \n",
    "        \n",
    "        return (data,columns)\n",
    "\n",
    "# Change background color of selected columns\n",
    "@app.callback(\n",
    "    Output('datatable-id', 'style_data_conditional'),\n",
    "    [Input('datatable-id', 'selected_columns')]\n",
    ")\n",
    "def update_styles(selected_columns):\n",
    "    return [{\n",
    "        'if': { 'column_id': i },\n",
    "        'background_color': '#b7e7da'\n",
    "    } for i in selected_columns]\n",
    "\n",
    "# Histogram chart for showing amount of animals available\n",
    "@app.callback(\n",
    "    Output('graph-id', \"children\"),\n",
    "    [Input('datatable-id', \"derived_viewport_data\"),\n",
    "    ])\n",
    "def update_graphs(viewData):\n",
    "    ###FIXED ####\n",
    "    dff = pd.DataFrame.from_dict(viewData)\n",
    "    \n",
    "    return [\n",
    "        dcc.Graph(\n",
    "            figure = px.histogram(dff, x='breed')\n",
    "        )    \n",
    "    ]\n",
    "\n",
    "# Geolocation map for idenitfying available animals\n",
    "@app.callback(\n",
    "    Output('map-id', \"children\"),\n",
    "    [Input('datatable-id', \"derived_viewport_data\"),\n",
    "     Input('datatable-id', 'derived_viewport_selected_rows')])\n",
    "def update_map(viewData, row_ids):\n",
    "    dff = pd.DataFrame.from_dict(viewData)\n",
    "    # Sets first num in row_ids array to the last selected row ID\n",
    "    row_ids[0] = row_ids[len(row_ids) - 1]\n",
    "    return [\n",
    "        # row_ids[0] gets last selected row from DataTable and parameters 13 and 14 are long and lat of rows\n",
    "        dl.Map(style={'width': '1000px', 'height': '500px'}, center=[dff.iloc[row_ids[0],13],dff.iloc[row_ids[0],14]], zoom=10, children=[\n",
    "            dl.TileLayer(id=\"base-layer-id\"),\n",
    "            # Marker with tool tip and popup\n",
    "            dl.Marker(position=[dff.iloc[row_ids[0],13],dff.iloc[row_ids[0],14]], children=[\n",
    "                # parameter num 4 gives the breed of animal\n",
    "                dl.Tooltip(dff.iloc[row_ids[0],4]),\n",
    "                dl.Popup([\n",
    "                    html.H1(\"Animal Name\"),\n",
    "                    # parameter 9 gives animal's name\n",
    "                    html.P(dff.iloc[row_ids[0],9])\n",
    "                ])\n",
    "            ])\n",
    "        ])\n",
    "    ]\n",
    "\n",
    "\n",
    "if __name__ == '__main__':\n",
    "    app.run_server(debug=False)"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {},
   "outputs": [],
   "source": []
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {},
   "outputs": [],
   "source": []
  }
 ],
 "metadata": {
  "kernelspec": {
   "display_name": "Python 3",
   "language": "python",
   "name": "python3"
  },
  "language_info": {
   "codemirror_mode": {
    "name": "ipython",
    "version": 3
   },
   "file_extension": ".py",
   "mimetype": "text/x-python",
   "name": "python",
   "nbconvert_exporter": "python",
   "pygments_lexer": "ipython3",
   "version": "3.6.9"
  }
 },
 "nbformat": 4,
 "nbformat_minor": 2
}
